### ISSUE TITLE
usar ctest

### ISSUE THREAD

**Issue by eltonfernando** [italonicacio/utilizando-cmake-para-organizar-seu-projeto-cpp#1]
seria possível executar os test com ctest?

**Comment by italonicacio** [comment]
Sim, é possível usar o Ctest. Inclusive, o ctest tem uma integração com o CMake. Você poder ver nesse [link](https://cmake.org/cmake/help/book/mastering-cmake/chapter/Testing%20With%20CMake%20and%20CTest.html).
