### ISSUE TITLE
vs code não reconhece gtest.h

### ISSUE THREAD

**Issue by eltonfernando** [italonicacio/utilizando-cmake-para-organizar-seu-projeto-cpp#2]
Como fazer para executar testes isolados

**Comment by italonicacio** [comment]
Para o vscode reconhecer o gtest.h você precisa da extensão para C/C++ que a microsoft fornece. Ai dentro da pasta _.vscode_ você cria um arquivo chamado _c_cpp_properties.json_, esse arquivo é responsável por configurar seu projeto C/C++ no vscode.

Em includePath você adiciona mais um caminho que seria o include do gtest. Se você usar as configurações abaixo deve funcionar. 

```cpp
{
	"configurations": [
		{
			"name": "Linux",
			"includePath": [
				"${workspaceFolder}/**",
				"${workspaceFolder}/build/_deps/googletest-src/googletest/include",
				"${workspaceFolder}/include"
			],
			"defines": [],
			"compilerPath": "/usr/bin/gcc",
			"cStandard": "c17",
			"cppStandard": "c++23",
			"intelliSenseMode": "linux-gcc-x64"
		}
	],
	"version": 4
}
```

**Comment by italonicacio** [comment]
Já para os testes isolados você pode usar o seguinte comando no terminal

`./myTest --gtest_filter="*<NomeDoTest>*" `

Esse parâmetro _-gtest_filter_ ele recebe algo semelhante a um regex, nunca testei muito a fundo, mas com asterisco ele pega tudo que tiver o <NomeDoTest>.

Por exemplo:

TEST(NomeDoTest_test, test1)
TEST(test_NomeDoTest_test, test2)
...
TEST(NomeDoTest, testn)

Tudo que tiver esse padrão ele vai executar. Basicamente é assim.
